spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springcloud?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 497903
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080 #在需要管理的微服务配置
      eager: true # 由加载变为快速加载
    openfeign:
      client:
        config:
          default:
            logger-level: full
            connect-timeout: 999999
            read-timeout: 9999999
          user-service:
            logger-level: full
            connect-timeout: 9999999
            read-timeout: 9999999
    nacos:
      server-addr: 127.0.0.1:8848
  application:
    name: userBook-service
server:
  port: 8002
#开启兜底返回
feign:
  sentinel:
    enabled: true

