spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springcloud?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 497903
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080 #在需要管理的微服务配置
      eager: true # 由加载变为快速加载
    nacos:
      server-addr: 127.0.0.1:8848
  application:
    name: user-service
server:
  port: 8001

